name: 'Notify Microsoft teams'
description: 'Notify to microsoft teams'
inputs:
  title:
    description: 'Title for the message'
    required: true
  text:
    description: 'Content of the message'
    required: false
  webhook_url:
    description: 'Microsoft webhook url'
    required: true
  action_link:
    description: 'URL to take an action on button click'
    required: false
  button_label:
    description: 'Label for the action button'
    required: false
  theme_color:
    description: 'Color for visual indication'
    required: false
  workflow_name:
    description: 'Workflow name'
    required: false
  workflow_run_number:
    description: 'Workflow run number'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Verify OS
      run: |
        if [[ $RUNNER_OS == 'Linux' ]]; then
          echo "isRunnerOSLinux=true" >> $GITHUB_OUTPUT
        else
          echo "isRunnerOSLinux=false" >> $GITHUB_OUTPUT
        fi
      id: verify-os
      shell: bash

    - if: ${{ steps.verify-os.outputs.isRunnerOSLinux != 'true'}}
      run: echo ${{steps.verify-os.outputs.isRunnerOSLinux}} 'This action runs only on Linux OS' && exit 1
      shell: bash

    - if: ${{ steps.verify-os.outputs.isRunnerOSLinux  == 'true' }}
      run: |
        chmod +x ${{github.action_path}}/entrypoint.sh
        ${{github.action_path}}/entrypoint.sh
      shell: bash
      env:
        Title: ${{inputs.title}}
        Text: ${{inputs.text}}
        WebhookUrl: ${{inputs.webhook_url}}
        ActionLink: ${{inputs.action_link}}
        ButtonLabel: ${{inputs.button_label}}
        ThemeColor: ${{inputs.theme_color}}
        WorkflowName: ${{inputs.workflow_name}}
        WorkflowRunNumber: ${{inputs.workflow_run_number}}
