name: Webapp CI

on:
  workflow_dispatch:

  pull_request:
    paths:
      - ui/packages/digital-twin/**
      - ui/cypress-E2E-tests/digital-twin-manager/**
    branches:
      - develop
      - release/r**.**

env:
  WORK_DIRECTORY: 'ui'

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test-webapp.yml
    with:
      test_command: 'yarn test:dtm'

  build-webapp:
    uses: ./.github/workflows/build-webapp.yml
    with:
      package_name: 'digital-twin'
      build_command: 'yarn build:dtm:ci'
      app_file_name_prefix: 'dtm-ui'
      app_context_path: 'digital-twin-manager'
      upload_artifact: true

  lint:
    uses: ./.github/workflows/linting-webapp.yml
    with:
      lint_command: 'yarn lint:dtm'
  
  lint-cypress:
    uses: ./.github/workflows/linting-cypress.yml
    with:
      lint_command: 'yarn test:lint'
      work_directory: 'ui/cypress-E2E-tests/digital-twin-manager'
