name: Widget - CI

on:
  workflow_dispatch:

  pull_request:
    paths:
      - asset-properties-widget/**
    branches:
      - develop

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test-widget.yml
    with:
      test_command: "yarn test"

  build-webapp:
    uses: ./.github/workflows/build-webapp.yml
    with:
      build_command: "yarn build"
      app_file_name_prefix: "asset-properties-widget"
      app_context_path: "asset-properties-widget"
      upload_artifact: true
