name: Widget - CI

on:
  workflow_dispatch:

  pull_request:
    paths:
      - asset-properties-widget/**
    branches:
      - develop

jobs:
  # unit-tests:
  #   uses: ./.github/workflows/unit-test-widget.yml
  #   with:
  #     test_command: "yarn test"

  build-widget:
    uses: ./.github/workflows/build-webapp.yml
    with:
      build_command: "yarn build"
      app_file_name_prefix: "sag-pkg-asset-properties-widget"
      app_context_path: "sag-pkg-asset-properties-widget"
      upload_artifact: true

  deploy:
    runs-on: [ubuntu-latest]
    needs: [build-widget]
    steps:
      - name: Create folder
        run: |
          if [[ ! -d "downloads" ]]; then
          mkdir downloads
          fi

      - name: Download webapp
        uses: actions/download-artifact@v3
        with:
          name: "sag-pkg-asset-properties-widget-1.0.0"
          path: "./downloads"

      - name: Deploy webapp
        uses: ./.github/workflows/c8y-deploy-action@v1.2
        with:
          TYPE: HOSTED
          PACKAGE_LOCATION: ${{ github.workspace }}/downloads/sag-pkg-asset-properties-widget-1.0.0.zip
          TENANT_URL: "https://dtmsecurity.latest.stage.c8y.io"
          AUTHORIZATION_CODE: "YXV0b3VzZXI6QXV0b3VzZXIyMUA="
          APPLICATION_NAME: "Asset properties widget"
          CONTEXT_PATH: "sag-pkg-asset-properties-widget"
          DELETE_EXISTING: false
